######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 11 00:25:13 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += FenPrincipale.h Highlighter.h MdiChild.h \
    codeeditor.h
SOURCES += FenPrincipale.cpp Highlighter.cpp main.cpp MdiChild.cpp \
    codeeditor.cpp
RC_FILE = anaspas_res.rc