######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 11 00:25:13 2008
######################################################################

TEMPLATE = app
TARGET = anaspas
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets
HEADERS += MainWindow.h Highlighter.h MdiChild.h  codeeditor.h
SOURCES += MainWindow.cpp Highlighter.cpp main.cpp MdiChild.cpp codeeditor.cpp
RC_FILE = anaspas_res.rc

RESOURCES += \
    res.qrc
